require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.0
  UseCache: true
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/bundle/**/*'
    - 'lib/tasks/*.rake'
    - 'spec/*_helper.rb'
    - 'config/*.rb'
    - !ruby/regexp /config/\w+/\b(?!doorkeeper\b)\w+.rb$/

Metrics/PerceivedComplexity:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Rails/EnumHash:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/VariableName:
  Enabled: false
