version: '3.8'
services:
  db:
    container_name: base_source_db
    image: postgres:9.4
    restart: always
    platform: linux/x86_64
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    command: -p 5432
  redis:
    image: redis:latest
    command: redis-server --bind redis --port 6379
  web:
    container_name: base_source_web
    build: .
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      BASE_SOURCE_DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0

      USE_MAILCATCHER: 1

    ports:
      - 3000:3000
    volumes:
      - .:/web
      - /web/vendor
      - /web/node_modules
    links:
      - db

      - mailcatcher

    stdin_open: true
    tty: true
    depends_on:
      - db
  sidekiq:
    container_name: base_source_sidekiq
    build: .
    command: bundle exec sidekiq
    environment:
      BASE_SOURCE_DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0

      USE_MAILCATCHER: 1

    volumes:
      - .:/web
      - /web/node_modules
    links:
      - redis
      - db

      - mailcatcher


  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'


volumes:
  db-data:
    driver: local
